/**
 * generated by Xtext 2.10.0
 */
package org.xtext.projet.selemodel.validation;

import org.xtext.projet.selemodel.validation.AbstractSelemodelValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SelemodelValidator extends AbstractSelemodelValidator {
}
