/*
 * generated by Xtext 2.10.0
 */
package org.xtext.projet.selemodel.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.projet.selemodel.parser.antlr.internal.InternalSelemodelParser;
import org.xtext.projet.selemodel.services.SelemodelGrammarAccess;

public class SelemodelParser extends AbstractAntlrParser {

	@Inject
	private SelemodelGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSelemodelParser createParser(XtextTokenStream stream) {
		return new InternalSelemodelParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public SelemodelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SelemodelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
