/**
 * generated by Xtext 2.10.0
 */
package org.xtext.projet.selemodel.selemodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.Action#getBrw <em>Brw</em>}</li>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.Action#getFil <em>Fil</em>}</li>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.Action#getCli <em>Cli</em>}</li>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.Action#getNav <em>Nav</em>}</li>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.Action#getCho <em>Cho</em>}</li>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.Action#getChe <em>Che</em>}</li>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.Action#getUnc <em>Unc</em>}</li>
 * </ul>
 *
 * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Brw</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Brw</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Brw</em>' containment reference.
   * @see #setBrw(OpenBrowser)
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getAction_Brw()
   * @model containment="true"
   * @generated
   */
  OpenBrowser getBrw();

  /**
   * Sets the value of the '{@link org.xtext.projet.selemodel.selemodel.Action#getBrw <em>Brw</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Brw</em>' containment reference.
   * @see #getBrw()
   * @generated
   */
  void setBrw(OpenBrowser value);

  /**
   * Returns the value of the '<em><b>Fil</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fil</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fil</em>' containment reference.
   * @see #setFil(Fill)
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getAction_Fil()
   * @model containment="true"
   * @generated
   */
  Fill getFil();

  /**
   * Sets the value of the '{@link org.xtext.projet.selemodel.selemodel.Action#getFil <em>Fil</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fil</em>' containment reference.
   * @see #getFil()
   * @generated
   */
  void setFil(Fill value);

  /**
   * Returns the value of the '<em><b>Cli</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cli</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cli</em>' containment reference.
   * @see #setCli(Click)
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getAction_Cli()
   * @model containment="true"
   * @generated
   */
  Click getCli();

  /**
   * Sets the value of the '{@link org.xtext.projet.selemodel.selemodel.Action#getCli <em>Cli</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cli</em>' containment reference.
   * @see #getCli()
   * @generated
   */
  void setCli(Click value);

  /**
   * Returns the value of the '<em><b>Nav</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Nav</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nav</em>' containment reference.
   * @see #setNav(Navigate)
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getAction_Nav()
   * @model containment="true"
   * @generated
   */
  Navigate getNav();

  /**
   * Sets the value of the '{@link org.xtext.projet.selemodel.selemodel.Action#getNav <em>Nav</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nav</em>' containment reference.
   * @see #getNav()
   * @generated
   */
  void setNav(Navigate value);

  /**
   * Returns the value of the '<em><b>Cho</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cho</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cho</em>' containment reference.
   * @see #setCho(Choose)
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getAction_Cho()
   * @model containment="true"
   * @generated
   */
  Choose getCho();

  /**
   * Sets the value of the '{@link org.xtext.projet.selemodel.selemodel.Action#getCho <em>Cho</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cho</em>' containment reference.
   * @see #getCho()
   * @generated
   */
  void setCho(Choose value);

  /**
   * Returns the value of the '<em><b>Che</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Che</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Che</em>' containment reference.
   * @see #setChe(Check)
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getAction_Che()
   * @model containment="true"
   * @generated
   */
  Check getChe();

  /**
   * Sets the value of the '{@link org.xtext.projet.selemodel.selemodel.Action#getChe <em>Che</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Che</em>' containment reference.
   * @see #getChe()
   * @generated
   */
  void setChe(Check value);

  /**
   * Returns the value of the '<em><b>Unc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unc</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unc</em>' containment reference.
   * @see #setUnc(Uncheck)
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getAction_Unc()
   * @model containment="true"
   * @generated
   */
  Uncheck getUnc();

  /**
   * Sets the value of the '{@link org.xtext.projet.selemodel.selemodel.Action#getUnc <em>Unc</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unc</em>' containment reference.
   * @see #getUnc()
   * @generated
   */
  void setUnc(Uncheck value);

} // Action
