/**
 * generated by Xtext 2.10.0
 */
package org.xtext.projet.selemodel.selemodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribution</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.Attribution#getVar <em>Var</em>}</li>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.Attribution#getAttb <em>Attb</em>}</li>
 * </ul>
 *
 * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getAttribution()
 * @model
 * @generated
 */
public interface Attribution extends EObject
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' reference.
   * @see #setVar(Var)
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getAttribution_Var()
   * @model
   * @generated
   */
  Var getVar();

  /**
   * Sets the value of the '{@link org.xtext.projet.selemodel.selemodel.Attribution#getVar <em>Var</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' reference.
   * @see #getVar()
   * @generated
   */
  void setVar(Var value);

  /**
   * Returns the value of the '<em><b>Attb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attb</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attb</em>' containment reference.
   * @see #setAttb(Attribuable)
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getAttribution_Attb()
   * @model containment="true"
   * @generated
   */
  Attribuable getAttb();

  /**
   * Sets the value of the '{@link org.xtext.projet.selemodel.selemodel.Attribution#getAttb <em>Attb</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attb</em>' containment reference.
   * @see #getAttb()
   * @generated
   */
  void setAttb(Attribuable value);

} // Attribution
