/**
 * generated by Xtext 2.10.0
 */
package org.xtext.projet.selemodel.selemodel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Container</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.Container#getTypeContainer <em>Type Container</em>}</li>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.Container#getConditions <em>Conditions</em>}</li>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.Container#getHierarchy <em>Hierarchy</em>}</li>
 * </ul>
 *
 * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getContainer()
 * @model
 * @generated
 */
public interface Container extends EObject
{
  /**
   * Returns the value of the '<em><b>Type Container</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Container</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Container</em>' attribute.
   * @see #setTypeContainer(String)
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getContainer_TypeContainer()
   * @model
   * @generated
   */
  String getTypeContainer();

  /**
   * Sets the value of the '{@link org.xtext.projet.selemodel.selemodel.Container#getTypeContainer <em>Type Container</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Container</em>' attribute.
   * @see #getTypeContainer()
   * @generated
   */
  void setTypeContainer(String value);

  /**
   * Returns the value of the '<em><b>Conditions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.projet.selemodel.selemodel.Condition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conditions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions</em>' containment reference list.
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getContainer_Conditions()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditions();

  /**
   * Returns the value of the '<em><b>Hierarchy</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Hierarchy</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hierarchy</em>' attribute list.
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getContainer_Hierarchy()
   * @model unique="false"
   * @generated
   */
  EList<String> getHierarchy();

} // Container
