/**
 * generated by Xtext 2.10.0
 */
package org.xtext.projet.selemodel.selemodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration Attribution</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.DeclarationAttribution#getDec <em>Dec</em>}</li>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.DeclarationAttribution#getAttb <em>Attb</em>}</li>
 * </ul>
 *
 * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getDeclarationAttribution()
 * @model
 * @generated
 */
public interface DeclarationAttribution extends EObject
{
  /**
   * Returns the value of the '<em><b>Dec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dec</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dec</em>' containment reference.
   * @see #setDec(Declaration)
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getDeclarationAttribution_Dec()
   * @model containment="true"
   * @generated
   */
  Declaration getDec();

  /**
   * Sets the value of the '{@link org.xtext.projet.selemodel.selemodel.DeclarationAttribution#getDec <em>Dec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dec</em>' containment reference.
   * @see #getDec()
   * @generated
   */
  void setDec(Declaration value);

  /**
   * Returns the value of the '<em><b>Attb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attb</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attb</em>' containment reference.
   * @see #setAttb(Attribuable)
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getDeclarationAttribution_Attb()
   * @model containment="true"
   * @generated
   */
  Attribuable getAttb();

  /**
   * Sets the value of the '{@link org.xtext.projet.selemodel.selemodel.DeclarationAttribution#getAttb <em>Attb</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attb</em>' containment reference.
   * @see #getAttb()
   * @generated
   */
  void setAttb(Attribuable value);

} // DeclarationAttribution
