/**
 * generated by Xtext 2.10.0
 */
package org.xtext.projet.selemodel.selemodel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.projet.selemodel.selemodel.SelemodelFactory
 * @model kind="package"
 * @generated
 */
public interface SelemodelPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "selemodel";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/projet/selemodel/Selemodel";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "selemodel";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SelemodelPackage eINSTANCE = org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.ModelImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Test</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TEST = 0;

  /**
   * The feature id for the '<em><b>Functions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__FUNCTIONS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.TestImpl <em>Test</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.TestImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getTest()
   * @generated
   */
  int TEST = 1;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST__EXPRESSIONS = 0;

  /**
   * The number of structural features of the '<em>Test</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.FunctionImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__PARAM = 1;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__EXPRESSIONS = 2;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.FunctionCallImpl <em>Function Call</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.FunctionCallImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getFunctionCall()
   * @generated
   */
  int FUNCTION_CALL = 3;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL__REF = 0;

  /**
   * The feature id for the '<em><b>Param</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL__PARAM = 1;

  /**
   * The number of structural features of the '<em>Function Call</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_CALL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.ExpressionImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 4;

  /**
   * The feature id for the '<em><b>Dec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__DEC = 0;

  /**
   * The feature id for the '<em><b>Att</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__ATT = 1;

  /**
   * The feature id for the '<em><b>Act</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__ACT = 2;

  /**
   * The feature id for the '<em><b>Ass</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__ASS = 3;

  /**
   * The feature id for the '<em><b>Fun</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__FUN = 4;

  /**
   * The feature id for the '<em><b>Decatt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION__DECATT = 5;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.AssertionImpl <em>Assertion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.AssertionImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getAssertion()
   * @generated
   */
  int ASSERTION = 5;

  /**
   * The feature id for the '<em><b>Att1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERTION__ATT1 = 0;

  /**
   * The feature id for the '<em><b>Att2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERTION__ATT2 = 1;

  /**
   * The feature id for the '<em><b>Con1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERTION__CON1 = 2;

  /**
   * The feature id for the '<em><b>Con2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERTION__CON2 = 3;

  /**
   * The number of structural features of the '<em>Assertion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERTION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.DeclarationImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 6;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__VAR = 0;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.DeclarationAttributionImpl <em>Declaration Attribution</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.DeclarationAttributionImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getDeclarationAttribution()
   * @generated
   */
  int DECLARATION_ATTRIBUTION = 7;

  /**
   * The feature id for the '<em><b>Dec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_ATTRIBUTION__DEC = 0;

  /**
   * The feature id for the '<em><b>Attb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_ATTRIBUTION__ATTB = 1;

  /**
   * The number of structural features of the '<em>Declaration Attribution</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_ATTRIBUTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.VarImpl <em>Var</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.VarImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getVar()
   * @generated
   */
  int VAR = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR__NAME = 0;

  /**
   * The number of structural features of the '<em>Var</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.AttribuableImpl <em>Attribuable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.AttribuableImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getAttribuable()
   * @generated
   */
  int ATTRIBUABLE = 9;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUABLE__STR = 0;

  /**
   * The feature id for the '<em><b>Attr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUABLE__ATTR = 1;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUABLE__REF = 2;

  /**
   * The number of structural features of the '<em>Attribuable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUABLE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.AttributionImpl <em>Attribution</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.AttributionImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getAttribution()
   * @generated
   */
  int ATTRIBUTION = 10;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTION__VAR = 0;

  /**
   * The feature id for the '<em><b>Attb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTION__ATTB = 1;

  /**
   * The number of structural features of the '<em>Attribution</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.AttributImpl <em>Attribut</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.AttributImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getAttribut()
   * @generated
   */
  int ATTRIBUT = 11;

  /**
   * The feature id for the '<em><b>Container</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUT__CONTAINER = 0;

  /**
   * The feature id for the '<em><b>Champ</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUT__CHAMP = 1;

  /**
   * The feature id for the '<em><b>Len</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUT__LEN = 2;

  /**
   * The feature id for the '<em><b>Containers</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUT__CONTAINERS = 3;

  /**
   * The number of structural features of the '<em>Attribut</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.ActionImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getAction()
   * @generated
   */
  int ACTION = 12;

  /**
   * The feature id for the '<em><b>Brw</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__BRW = 0;

  /**
   * The feature id for the '<em><b>Fil</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__FIL = 1;

  /**
   * The feature id for the '<em><b>Cli</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__CLI = 2;

  /**
   * The feature id for the '<em><b>Nav</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__NAV = 3;

  /**
   * The feature id for the '<em><b>Cho</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__CHO = 4;

  /**
   * The feature id for the '<em><b>Che</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__CHE = 5;

  /**
   * The feature id for the '<em><b>Unc</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__UNC = 6;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.FillImpl <em>Fill</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.FillImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getFill()
   * @generated
   */
  int FILL = 13;

  /**
   * The feature id for the '<em><b>Container</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__CONTAINER = 0;

  /**
   * The feature id for the '<em><b>Attb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL__ATTB = 1;

  /**
   * The number of structural features of the '<em>Fill</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.ClickImpl <em>Click</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.ClickImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getClick()
   * @generated
   */
  int CLICK = 14;

  /**
   * The feature id for the '<em><b>Container</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK__CONTAINER = 0;

  /**
   * The number of structural features of the '<em>Click</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLICK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.NavigateImpl <em>Navigate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.NavigateImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getNavigate()
   * @generated
   */
  int NAVIGATE = 15;

  /**
   * The feature id for the '<em><b>Attb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAVIGATE__ATTB = 0;

  /**
   * The number of structural features of the '<em>Navigate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAVIGATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.ChooseImpl <em>Choose</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.ChooseImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getChoose()
   * @generated
   */
  int CHOOSE = 16;

  /**
   * The feature id for the '<em><b>Container</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOOSE__CONTAINER = 0;

  /**
   * The feature id for the '<em><b>Attb</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOOSE__ATTB = 1;

  /**
   * The number of structural features of the '<em>Choose</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHOOSE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.CheckImpl <em>Check</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.CheckImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getCheck()
   * @generated
   */
  int CHECK = 17;

  /**
   * The feature id for the '<em><b>Container</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__CONTAINER = 0;

  /**
   * The feature id for the '<em><b>Containers</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK__CONTAINERS = 1;

  /**
   * The number of structural features of the '<em>Check</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHECK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.UncheckImpl <em>Uncheck</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.UncheckImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getUncheck()
   * @generated
   */
  int UNCHECK = 18;

  /**
   * The feature id for the '<em><b>Container</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNCHECK__CONTAINER = 0;

  /**
   * The feature id for the '<em><b>Containers</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNCHECK__CONTAINERS = 1;

  /**
   * The number of structural features of the '<em>Uncheck</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNCHECK_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.OpenBrowserImpl <em>Open Browser</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.OpenBrowserImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getOpenBrowser()
   * @generated
   */
  int OPEN_BROWSER = 19;

  /**
   * The feature id for the '<em><b>Browser</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_BROWSER__BROWSER = 0;

  /**
   * The number of structural features of the '<em>Open Browser</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPEN_BROWSER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.ContainerImpl <em>Container</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.ContainerImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getContainer()
   * @generated
   */
  int CONTAINER = 20;

  /**
   * The feature id for the '<em><b>Type Container</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__TYPE_CONTAINER = 0;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__CONDITIONS = 1;

  /**
   * The feature id for the '<em><b>Hierarchy</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER__HIERARCHY = 2;

  /**
   * The number of structural features of the '<em>Container</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.ContainersImpl <em>Containers</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.ContainersImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getContainers()
   * @generated
   */
  int CONTAINERS = 21;

  /**
   * The feature id for the '<em><b>Type Container</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINERS__TYPE_CONTAINER = 0;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINERS__CONDITIONS = 1;

  /**
   * The number of structural features of the '<em>Containers</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINERS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.projet.selemodel.selemodel.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.projet.selemodel.selemodel.impl.ConditionImpl
   * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 22;

  /**
   * The feature id for the '<em><b>Champ</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__CHAMP = 0;

  /**
   * The feature id for the '<em><b>Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__STR = 1;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__REF = 2;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.projet.selemodel.selemodel.Model#getTest <em>Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Test</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Model#getTest()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Test();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.projet.selemodel.selemodel.Model#getFunctions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Functions</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Model#getFunctions()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Functions();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Test <em>Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Test
   * @generated
   */
  EClass getTest();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.projet.selemodel.selemodel.Test#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Test#getExpressions()
   * @see #getTest()
   * @generated
   */
  EReference getTest_Expressions();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projet.selemodel.selemodel.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.projet.selemodel.selemodel.Function#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Param</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Function#getParam()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Param();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.projet.selemodel.selemodel.Function#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Function#getExpressions()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Expressions();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.FunctionCall <em>Function Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function Call</em>'.
   * @see org.xtext.projet.selemodel.selemodel.FunctionCall
   * @generated
   */
  EClass getFunctionCall();

  /**
   * Returns the meta object for the reference '{@link org.xtext.projet.selemodel.selemodel.FunctionCall#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see org.xtext.projet.selemodel.selemodel.FunctionCall#getRef()
   * @see #getFunctionCall()
   * @generated
   */
  EReference getFunctionCall_Ref();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.projet.selemodel.selemodel.FunctionCall#getParam <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Param</em>'.
   * @see org.xtext.projet.selemodel.selemodel.FunctionCall#getParam()
   * @see #getFunctionCall()
   * @generated
   */
  EReference getFunctionCall_Param();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Expression#getDec <em>Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dec</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Expression#getDec()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Dec();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Expression#getAtt <em>Att</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Att</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Expression#getAtt()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Att();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Expression#getAct <em>Act</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Act</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Expression#getAct()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Act();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Expression#getAss <em>Ass</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ass</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Expression#getAss()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Ass();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Expression#getFun <em>Fun</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fun</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Expression#getFun()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Fun();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Expression#getDecatt <em>Decatt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Decatt</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Expression#getDecatt()
   * @see #getExpression()
   * @generated
   */
  EReference getExpression_Decatt();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Assertion <em>Assertion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assertion</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Assertion
   * @generated
   */
  EClass getAssertion();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Assertion#getAtt1 <em>Att1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Att1</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Assertion#getAtt1()
   * @see #getAssertion()
   * @generated
   */
  EReference getAssertion_Att1();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Assertion#getAtt2 <em>Att2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Att2</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Assertion#getAtt2()
   * @see #getAssertion()
   * @generated
   */
  EReference getAssertion_Att2();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Assertion#getCon1 <em>Con1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Con1</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Assertion#getCon1()
   * @see #getAssertion()
   * @generated
   */
  EReference getAssertion_Con1();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Assertion#getCon2 <em>Con2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Con2</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Assertion#getCon2()
   * @see #getAssertion()
   * @generated
   */
  EReference getAssertion_Con2();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Declaration#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Declaration#getVar()
   * @see #getDeclaration()
   * @generated
   */
  EReference getDeclaration_Var();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.DeclarationAttribution <em>Declaration Attribution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration Attribution</em>'.
   * @see org.xtext.projet.selemodel.selemodel.DeclarationAttribution
   * @generated
   */
  EClass getDeclarationAttribution();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.DeclarationAttribution#getDec <em>Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dec</em>'.
   * @see org.xtext.projet.selemodel.selemodel.DeclarationAttribution#getDec()
   * @see #getDeclarationAttribution()
   * @generated
   */
  EReference getDeclarationAttribution_Dec();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.DeclarationAttribution#getAttb <em>Attb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attb</em>'.
   * @see org.xtext.projet.selemodel.selemodel.DeclarationAttribution#getAttb()
   * @see #getDeclarationAttribution()
   * @generated
   */
  EReference getDeclarationAttribution_Attb();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Var <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Var
   * @generated
   */
  EClass getVar();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projet.selemodel.selemodel.Var#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Var#getName()
   * @see #getVar()
   * @generated
   */
  EAttribute getVar_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Attribuable <em>Attribuable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribuable</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Attribuable
   * @generated
   */
  EClass getAttribuable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projet.selemodel.selemodel.Attribuable#getStr <em>Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Str</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Attribuable#getStr()
   * @see #getAttribuable()
   * @generated
   */
  EAttribute getAttribuable_Str();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Attribuable#getAttr <em>Attr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attr</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Attribuable#getAttr()
   * @see #getAttribuable()
   * @generated
   */
  EReference getAttribuable_Attr();

  /**
   * Returns the meta object for the reference '{@link org.xtext.projet.selemodel.selemodel.Attribuable#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Attribuable#getRef()
   * @see #getAttribuable()
   * @generated
   */
  EReference getAttribuable_Ref();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Attribution <em>Attribution</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribution</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Attribution
   * @generated
   */
  EClass getAttribution();

  /**
   * Returns the meta object for the reference '{@link org.xtext.projet.selemodel.selemodel.Attribution#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Attribution#getVar()
   * @see #getAttribution()
   * @generated
   */
  EReference getAttribution_Var();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Attribution#getAttb <em>Attb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attb</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Attribution#getAttb()
   * @see #getAttribution()
   * @generated
   */
  EReference getAttribution_Attb();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Attribut <em>Attribut</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribut</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Attribut
   * @generated
   */
  EClass getAttribut();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Attribut#getContainer <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Container</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Attribut#getContainer()
   * @see #getAttribut()
   * @generated
   */
  EReference getAttribut_Container();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projet.selemodel.selemodel.Attribut#getChamp <em>Champ</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Champ</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Attribut#getChamp()
   * @see #getAttribut()
   * @generated
   */
  EAttribute getAttribut_Champ();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projet.selemodel.selemodel.Attribut#getLen <em>Len</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Len</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Attribut#getLen()
   * @see #getAttribut()
   * @generated
   */
  EAttribute getAttribut_Len();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Attribut#getContainers <em>Containers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Containers</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Attribut#getContainers()
   * @see #getAttribut()
   * @generated
   */
  EReference getAttribut_Containers();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Action#getBrw <em>Brw</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Brw</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Action#getBrw()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Brw();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Action#getFil <em>Fil</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fil</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Action#getFil()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Fil();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Action#getCli <em>Cli</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cli</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Action#getCli()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Cli();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Action#getNav <em>Nav</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nav</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Action#getNav()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Nav();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Action#getCho <em>Cho</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cho</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Action#getCho()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Cho();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Action#getChe <em>Che</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Che</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Action#getChe()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Che();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Action#getUnc <em>Unc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Unc</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Action#getUnc()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Unc();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Fill <em>Fill</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fill</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Fill
   * @generated
   */
  EClass getFill();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Fill#getContainer <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Container</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Fill#getContainer()
   * @see #getFill()
   * @generated
   */
  EReference getFill_Container();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Fill#getAttb <em>Attb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attb</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Fill#getAttb()
   * @see #getFill()
   * @generated
   */
  EReference getFill_Attb();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Click <em>Click</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Click</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Click
   * @generated
   */
  EClass getClick();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Click#getContainer <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Container</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Click#getContainer()
   * @see #getClick()
   * @generated
   */
  EReference getClick_Container();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Navigate <em>Navigate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Navigate</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Navigate
   * @generated
   */
  EClass getNavigate();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Navigate#getAttb <em>Attb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attb</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Navigate#getAttb()
   * @see #getNavigate()
   * @generated
   */
  EReference getNavigate_Attb();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Choose <em>Choose</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Choose</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Choose
   * @generated
   */
  EClass getChoose();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Choose#getContainer <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Container</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Choose#getContainer()
   * @see #getChoose()
   * @generated
   */
  EReference getChoose_Container();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Choose#getAttb <em>Attb</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Attb</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Choose#getAttb()
   * @see #getChoose()
   * @generated
   */
  EReference getChoose_Attb();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Check <em>Check</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Check</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Check
   * @generated
   */
  EClass getCheck();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Check#getContainer <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Container</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Check#getContainer()
   * @see #getCheck()
   * @generated
   */
  EReference getCheck_Container();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Check#getContainers <em>Containers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Containers</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Check#getContainers()
   * @see #getCheck()
   * @generated
   */
  EReference getCheck_Containers();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Uncheck <em>Uncheck</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Uncheck</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Uncheck
   * @generated
   */
  EClass getUncheck();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Uncheck#getContainer <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Container</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Uncheck#getContainer()
   * @see #getUncheck()
   * @generated
   */
  EReference getUncheck_Container();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.projet.selemodel.selemodel.Uncheck#getContainers <em>Containers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Containers</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Uncheck#getContainers()
   * @see #getUncheck()
   * @generated
   */
  EReference getUncheck_Containers();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.OpenBrowser <em>Open Browser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Open Browser</em>'.
   * @see org.xtext.projet.selemodel.selemodel.OpenBrowser
   * @generated
   */
  EClass getOpenBrowser();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projet.selemodel.selemodel.OpenBrowser#getBrowser <em>Browser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Browser</em>'.
   * @see org.xtext.projet.selemodel.selemodel.OpenBrowser#getBrowser()
   * @see #getOpenBrowser()
   * @generated
   */
  EAttribute getOpenBrowser_Browser();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Container <em>Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Container</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Container
   * @generated
   */
  EClass getContainer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projet.selemodel.selemodel.Container#getTypeContainer <em>Type Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type Container</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Container#getTypeContainer()
   * @see #getContainer()
   * @generated
   */
  EAttribute getContainer_TypeContainer();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.projet.selemodel.selemodel.Container#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Conditions</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Container#getConditions()
   * @see #getContainer()
   * @generated
   */
  EReference getContainer_Conditions();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.projet.selemodel.selemodel.Container#getHierarchy <em>Hierarchy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Hierarchy</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Container#getHierarchy()
   * @see #getContainer()
   * @generated
   */
  EAttribute getContainer_Hierarchy();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Containers <em>Containers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Containers</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Containers
   * @generated
   */
  EClass getContainers();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projet.selemodel.selemodel.Containers#getTypeContainer <em>Type Container</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type Container</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Containers#getTypeContainer()
   * @see #getContainers()
   * @generated
   */
  EAttribute getContainers_TypeContainer();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.projet.selemodel.selemodel.Containers#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Conditions</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Containers#getConditions()
   * @see #getContainers()
   * @generated
   */
  EReference getContainers_Conditions();

  /**
   * Returns the meta object for class '{@link org.xtext.projet.selemodel.selemodel.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projet.selemodel.selemodel.Condition#getChamp <em>Champ</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Champ</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Condition#getChamp()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Champ();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.projet.selemodel.selemodel.Condition#getStr <em>Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Str</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Condition#getStr()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Str();

  /**
   * Returns the meta object for the reference '{@link org.xtext.projet.selemodel.selemodel.Condition#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see org.xtext.projet.selemodel.selemodel.Condition#getRef()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Ref();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SelemodelFactory getSelemodelFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.ModelImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Test</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__TEST = eINSTANCE.getModel_Test();

    /**
     * The meta object literal for the '<em><b>Functions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__FUNCTIONS = eINSTANCE.getModel_Functions();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.TestImpl <em>Test</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.TestImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getTest()
     * @generated
     */
    EClass TEST = eINSTANCE.getTest();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TEST__EXPRESSIONS = eINSTANCE.getTest_Expressions();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.FunctionImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__PARAM = eINSTANCE.getFunction_Param();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__EXPRESSIONS = eINSTANCE.getFunction_Expressions();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.FunctionCallImpl <em>Function Call</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.FunctionCallImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getFunctionCall()
     * @generated
     */
    EClass FUNCTION_CALL = eINSTANCE.getFunctionCall();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL__REF = eINSTANCE.getFunctionCall_Ref();

    /**
     * The meta object literal for the '<em><b>Param</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION_CALL__PARAM = eINSTANCE.getFunctionCall_Param();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.ExpressionImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '<em><b>Dec</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__DEC = eINSTANCE.getExpression_Dec();

    /**
     * The meta object literal for the '<em><b>Att</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__ATT = eINSTANCE.getExpression_Att();

    /**
     * The meta object literal for the '<em><b>Act</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__ACT = eINSTANCE.getExpression_Act();

    /**
     * The meta object literal for the '<em><b>Ass</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__ASS = eINSTANCE.getExpression_Ass();

    /**
     * The meta object literal for the '<em><b>Fun</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__FUN = eINSTANCE.getExpression_Fun();

    /**
     * The meta object literal for the '<em><b>Decatt</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPRESSION__DECATT = eINSTANCE.getExpression_Decatt();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.AssertionImpl <em>Assertion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.AssertionImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getAssertion()
     * @generated
     */
    EClass ASSERTION = eINSTANCE.getAssertion();

    /**
     * The meta object literal for the '<em><b>Att1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSERTION__ATT1 = eINSTANCE.getAssertion_Att1();

    /**
     * The meta object literal for the '<em><b>Att2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSERTION__ATT2 = eINSTANCE.getAssertion_Att2();

    /**
     * The meta object literal for the '<em><b>Con1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSERTION__CON1 = eINSTANCE.getAssertion_Con1();

    /**
     * The meta object literal for the '<em><b>Con2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSERTION__CON2 = eINSTANCE.getAssertion_Con2();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.DeclarationImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARATION__VAR = eINSTANCE.getDeclaration_Var();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.DeclarationAttributionImpl <em>Declaration Attribution</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.DeclarationAttributionImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getDeclarationAttribution()
     * @generated
     */
    EClass DECLARATION_ATTRIBUTION = eINSTANCE.getDeclarationAttribution();

    /**
     * The meta object literal for the '<em><b>Dec</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARATION_ATTRIBUTION__DEC = eINSTANCE.getDeclarationAttribution_Dec();

    /**
     * The meta object literal for the '<em><b>Attb</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARATION_ATTRIBUTION__ATTB = eINSTANCE.getDeclarationAttribution_Attb();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.VarImpl <em>Var</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.VarImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getVar()
     * @generated
     */
    EClass VAR = eINSTANCE.getVar();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR__NAME = eINSTANCE.getVar_Name();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.AttribuableImpl <em>Attribuable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.AttribuableImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getAttribuable()
     * @generated
     */
    EClass ATTRIBUABLE = eINSTANCE.getAttribuable();

    /**
     * The meta object literal for the '<em><b>Str</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUABLE__STR = eINSTANCE.getAttribuable_Str();

    /**
     * The meta object literal for the '<em><b>Attr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUABLE__ATTR = eINSTANCE.getAttribuable_Attr();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUABLE__REF = eINSTANCE.getAttribuable_Ref();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.AttributionImpl <em>Attribution</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.AttributionImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getAttribution()
     * @generated
     */
    EClass ATTRIBUTION = eINSTANCE.getAttribution();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTION__VAR = eINSTANCE.getAttribution_Var();

    /**
     * The meta object literal for the '<em><b>Attb</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTION__ATTB = eINSTANCE.getAttribution_Attb();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.AttributImpl <em>Attribut</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.AttributImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getAttribut()
     * @generated
     */
    EClass ATTRIBUT = eINSTANCE.getAttribut();

    /**
     * The meta object literal for the '<em><b>Container</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUT__CONTAINER = eINSTANCE.getAttribut_Container();

    /**
     * The meta object literal for the '<em><b>Champ</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUT__CHAMP = eINSTANCE.getAttribut_Champ();

    /**
     * The meta object literal for the '<em><b>Len</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUT__LEN = eINSTANCE.getAttribut_Len();

    /**
     * The meta object literal for the '<em><b>Containers</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUT__CONTAINERS = eINSTANCE.getAttribut_Containers();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.ActionImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Brw</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__BRW = eINSTANCE.getAction_Brw();

    /**
     * The meta object literal for the '<em><b>Fil</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__FIL = eINSTANCE.getAction_Fil();

    /**
     * The meta object literal for the '<em><b>Cli</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__CLI = eINSTANCE.getAction_Cli();

    /**
     * The meta object literal for the '<em><b>Nav</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__NAV = eINSTANCE.getAction_Nav();

    /**
     * The meta object literal for the '<em><b>Cho</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__CHO = eINSTANCE.getAction_Cho();

    /**
     * The meta object literal for the '<em><b>Che</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__CHE = eINSTANCE.getAction_Che();

    /**
     * The meta object literal for the '<em><b>Unc</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__UNC = eINSTANCE.getAction_Unc();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.FillImpl <em>Fill</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.FillImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getFill()
     * @generated
     */
    EClass FILL = eINSTANCE.getFill();

    /**
     * The meta object literal for the '<em><b>Container</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILL__CONTAINER = eINSTANCE.getFill_Container();

    /**
     * The meta object literal for the '<em><b>Attb</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILL__ATTB = eINSTANCE.getFill_Attb();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.ClickImpl <em>Click</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.ClickImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getClick()
     * @generated
     */
    EClass CLICK = eINSTANCE.getClick();

    /**
     * The meta object literal for the '<em><b>Container</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLICK__CONTAINER = eINSTANCE.getClick_Container();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.NavigateImpl <em>Navigate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.NavigateImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getNavigate()
     * @generated
     */
    EClass NAVIGATE = eINSTANCE.getNavigate();

    /**
     * The meta object literal for the '<em><b>Attb</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NAVIGATE__ATTB = eINSTANCE.getNavigate_Attb();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.ChooseImpl <em>Choose</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.ChooseImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getChoose()
     * @generated
     */
    EClass CHOOSE = eINSTANCE.getChoose();

    /**
     * The meta object literal for the '<em><b>Container</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOOSE__CONTAINER = eINSTANCE.getChoose_Container();

    /**
     * The meta object literal for the '<em><b>Attb</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHOOSE__ATTB = eINSTANCE.getChoose_Attb();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.CheckImpl <em>Check</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.CheckImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getCheck()
     * @generated
     */
    EClass CHECK = eINSTANCE.getCheck();

    /**
     * The meta object literal for the '<em><b>Container</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK__CONTAINER = eINSTANCE.getCheck_Container();

    /**
     * The meta object literal for the '<em><b>Containers</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHECK__CONTAINERS = eINSTANCE.getCheck_Containers();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.UncheckImpl <em>Uncheck</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.UncheckImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getUncheck()
     * @generated
     */
    EClass UNCHECK = eINSTANCE.getUncheck();

    /**
     * The meta object literal for the '<em><b>Container</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNCHECK__CONTAINER = eINSTANCE.getUncheck_Container();

    /**
     * The meta object literal for the '<em><b>Containers</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNCHECK__CONTAINERS = eINSTANCE.getUncheck_Containers();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.OpenBrowserImpl <em>Open Browser</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.OpenBrowserImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getOpenBrowser()
     * @generated
     */
    EClass OPEN_BROWSER = eINSTANCE.getOpenBrowser();

    /**
     * The meta object literal for the '<em><b>Browser</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OPEN_BROWSER__BROWSER = eINSTANCE.getOpenBrowser_Browser();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.ContainerImpl <em>Container</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.ContainerImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getContainer()
     * @generated
     */
    EClass CONTAINER = eINSTANCE.getContainer();

    /**
     * The meta object literal for the '<em><b>Type Container</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTAINER__TYPE_CONTAINER = eINSTANCE.getContainer_TypeContainer();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTAINER__CONDITIONS = eINSTANCE.getContainer_Conditions();

    /**
     * The meta object literal for the '<em><b>Hierarchy</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTAINER__HIERARCHY = eINSTANCE.getContainer_Hierarchy();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.ContainersImpl <em>Containers</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.ContainersImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getContainers()
     * @generated
     */
    EClass CONTAINERS = eINSTANCE.getContainers();

    /**
     * The meta object literal for the '<em><b>Type Container</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTAINERS__TYPE_CONTAINER = eINSTANCE.getContainers_TypeContainer();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTAINERS__CONDITIONS = eINSTANCE.getContainers_Conditions();

    /**
     * The meta object literal for the '{@link org.xtext.projet.selemodel.selemodel.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.projet.selemodel.selemodel.impl.ConditionImpl
     * @see org.xtext.projet.selemodel.selemodel.impl.SelemodelPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Champ</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__CHAMP = eINSTANCE.getCondition_Champ();

    /**
     * The meta object literal for the '<em><b>Str</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__STR = eINSTANCE.getCondition_Str();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__REF = eINSTANCE.getCondition_Ref();

  }

} //SelemodelPackage
