/**
 * generated by Xtext 2.10.0
 */
package org.xtext.projet.selemodel.selemodel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Uncheck</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.Uncheck#getContainer <em>Container</em>}</li>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.Uncheck#getContainers <em>Containers</em>}</li>
 * </ul>
 *
 * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getUncheck()
 * @model
 * @generated
 */
public interface Uncheck extends EObject
{
  /**
   * Returns the value of the '<em><b>Container</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Container</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Container</em>' containment reference.
   * @see #setContainer(Container)
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getUncheck_Container()
   * @model containment="true"
   * @generated
   */
  Container getContainer();

  /**
   * Sets the value of the '{@link org.xtext.projet.selemodel.selemodel.Uncheck#getContainer <em>Container</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Container</em>' containment reference.
   * @see #getContainer()
   * @generated
   */
  void setContainer(Container value);

  /**
   * Returns the value of the '<em><b>Containers</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Containers</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Containers</em>' containment reference.
   * @see #setContainers(Containers)
   * @see org.xtext.projet.selemodel.selemodel.SelemodelPackage#getUncheck_Containers()
   * @model containment="true"
   * @generated
   */
  Containers getContainers();

  /**
   * Sets the value of the '{@link org.xtext.projet.selemodel.selemodel.Uncheck#getContainers <em>Containers</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Containers</em>' containment reference.
   * @see #getContainers()
   * @generated
   */
  void setContainers(Containers value);

} // Uncheck
