/**
 * generated by Xtext 2.10.0
 */
package org.xtext.selenium.selemodel;

import org.xtext.selenium.selemodel.AbstractSeleModelRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SeleModelRuntimeModule extends AbstractSeleModelRuntimeModule {
}
