/**
 * generated by Xtext 2.10.0
 */
package org.xtext.projet.selemodel;

import org.xtext.projet.selemodel.AbstractSelemodelRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SelemodelRuntimeModule extends AbstractSelemodelRuntimeModule {
}
