/**
 * generated by Xtext 2.10.0
 */
package org.xtext.selenium.selemodel.seleModel.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.selenium.selemodel.seleModel.Condition;
import org.xtext.selenium.selemodel.seleModel.Containers;
import org.xtext.selenium.selemodel.seleModel.SeleModelPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Containers</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.selenium.selemodel.seleModel.impl.ContainersImpl#getTypeContainer <em>Type Container</em>}</li>
 *   <li>{@link org.xtext.selenium.selemodel.seleModel.impl.ContainersImpl#getConditions <em>Conditions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ContainersImpl extends MinimalEObjectImpl.Container implements Containers
{
  /**
   * The default value of the '{@link #getTypeContainer() <em>Type Container</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeContainer()
   * @generated
   * @ordered
   */
  protected static final String TYPE_CONTAINER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTypeContainer() <em>Type Container</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeContainer()
   * @generated
   * @ordered
   */
  protected String typeContainer = TYPE_CONTAINER_EDEFAULT;

  /**
   * The cached value of the '{@link #getConditions() <em>Conditions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConditions()
   * @generated
   * @ordered
   */
  protected EList<Condition> conditions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ContainersImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SeleModelPackage.Literals.CONTAINERS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTypeContainer()
  {
    return typeContainer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTypeContainer(String newTypeContainer)
  {
    String oldTypeContainer = typeContainer;
    typeContainer = newTypeContainer;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SeleModelPackage.CONTAINERS__TYPE_CONTAINER, oldTypeContainer, typeContainer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Condition> getConditions()
  {
    if (conditions == null)
    {
      conditions = new EObjectContainmentEList<Condition>(Condition.class, this, SeleModelPackage.CONTAINERS__CONDITIONS);
    }
    return conditions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SeleModelPackage.CONTAINERS__CONDITIONS:
        return ((InternalEList<?>)getConditions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SeleModelPackage.CONTAINERS__TYPE_CONTAINER:
        return getTypeContainer();
      case SeleModelPackage.CONTAINERS__CONDITIONS:
        return getConditions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SeleModelPackage.CONTAINERS__TYPE_CONTAINER:
        setTypeContainer((String)newValue);
        return;
      case SeleModelPackage.CONTAINERS__CONDITIONS:
        getConditions().clear();
        getConditions().addAll((Collection<? extends Condition>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SeleModelPackage.CONTAINERS__TYPE_CONTAINER:
        setTypeContainer(TYPE_CONTAINER_EDEFAULT);
        return;
      case SeleModelPackage.CONTAINERS__CONDITIONS:
        getConditions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SeleModelPackage.CONTAINERS__TYPE_CONTAINER:
        return TYPE_CONTAINER_EDEFAULT == null ? typeContainer != null : !TYPE_CONTAINER_EDEFAULT.equals(typeContainer);
      case SeleModelPackage.CONTAINERS__CONDITIONS:
        return conditions != null && !conditions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (typeContainer: ");
    result.append(typeContainer);
    result.append(')');
    return result.toString();
  }

} //ContainersImpl
