/**
 * generated by Xtext 2.10.0
 */
package org.xtext.projet.selemodel.selemodel.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.projet.selemodel.selemodel.Attribut;
import org.xtext.projet.selemodel.selemodel.Containers;
import org.xtext.projet.selemodel.selemodel.SelemodelPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribut</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.impl.AttributImpl#getContainer <em>Container</em>}</li>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.impl.AttributImpl#getChamp <em>Champ</em>}</li>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.impl.AttributImpl#getLen <em>Len</em>}</li>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.impl.AttributImpl#getContainers <em>Containers</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AttributImpl extends MinimalEObjectImpl.Container implements Attribut
{
  /**
   * The cached value of the '{@link #getContainer() <em>Container</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContainer()
   * @generated
   * @ordered
   */
  protected org.xtext.projet.selemodel.selemodel.Container container;

  /**
   * The default value of the '{@link #getChamp() <em>Champ</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChamp()
   * @generated
   * @ordered
   */
  protected static final String CHAMP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getChamp() <em>Champ</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChamp()
   * @generated
   * @ordered
   */
  protected String champ = CHAMP_EDEFAULT;

  /**
   * The default value of the '{@link #getLen() <em>Len</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLen()
   * @generated
   * @ordered
   */
  protected static final String LEN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLen() <em>Len</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLen()
   * @generated
   * @ordered
   */
  protected String len = LEN_EDEFAULT;

  /**
   * The cached value of the '{@link #getContainers() <em>Containers</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContainers()
   * @generated
   * @ordered
   */
  protected Containers containers;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SelemodelPackage.Literals.ATTRIBUT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public org.xtext.projet.selemodel.selemodel.Container getContainer()
  {
    return container;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetContainer(org.xtext.projet.selemodel.selemodel.Container newContainer, NotificationChain msgs)
  {
    org.xtext.projet.selemodel.selemodel.Container oldContainer = container;
    container = newContainer;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SelemodelPackage.ATTRIBUT__CONTAINER, oldContainer, newContainer);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setContainer(org.xtext.projet.selemodel.selemodel.Container newContainer)
  {
    if (newContainer != container)
    {
      NotificationChain msgs = null;
      if (container != null)
        msgs = ((InternalEObject)container).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SelemodelPackage.ATTRIBUT__CONTAINER, null, msgs);
      if (newContainer != null)
        msgs = ((InternalEObject)newContainer).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SelemodelPackage.ATTRIBUT__CONTAINER, null, msgs);
      msgs = basicSetContainer(newContainer, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SelemodelPackage.ATTRIBUT__CONTAINER, newContainer, newContainer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getChamp()
  {
    return champ;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setChamp(String newChamp)
  {
    String oldChamp = champ;
    champ = newChamp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SelemodelPackage.ATTRIBUT__CHAMP, oldChamp, champ));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLen()
  {
    return len;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLen(String newLen)
  {
    String oldLen = len;
    len = newLen;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SelemodelPackage.ATTRIBUT__LEN, oldLen, len));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Containers getContainers()
  {
    return containers;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetContainers(Containers newContainers, NotificationChain msgs)
  {
    Containers oldContainers = containers;
    containers = newContainers;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SelemodelPackage.ATTRIBUT__CONTAINERS, oldContainers, newContainers);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setContainers(Containers newContainers)
  {
    if (newContainers != containers)
    {
      NotificationChain msgs = null;
      if (containers != null)
        msgs = ((InternalEObject)containers).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SelemodelPackage.ATTRIBUT__CONTAINERS, null, msgs);
      if (newContainers != null)
        msgs = ((InternalEObject)newContainers).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SelemodelPackage.ATTRIBUT__CONTAINERS, null, msgs);
      msgs = basicSetContainers(newContainers, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SelemodelPackage.ATTRIBUT__CONTAINERS, newContainers, newContainers));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SelemodelPackage.ATTRIBUT__CONTAINER:
        return basicSetContainer(null, msgs);
      case SelemodelPackage.ATTRIBUT__CONTAINERS:
        return basicSetContainers(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SelemodelPackage.ATTRIBUT__CONTAINER:
        return getContainer();
      case SelemodelPackage.ATTRIBUT__CHAMP:
        return getChamp();
      case SelemodelPackage.ATTRIBUT__LEN:
        return getLen();
      case SelemodelPackage.ATTRIBUT__CONTAINERS:
        return getContainers();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SelemodelPackage.ATTRIBUT__CONTAINER:
        setContainer((org.xtext.projet.selemodel.selemodel.Container)newValue);
        return;
      case SelemodelPackage.ATTRIBUT__CHAMP:
        setChamp((String)newValue);
        return;
      case SelemodelPackage.ATTRIBUT__LEN:
        setLen((String)newValue);
        return;
      case SelemodelPackage.ATTRIBUT__CONTAINERS:
        setContainers((Containers)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SelemodelPackage.ATTRIBUT__CONTAINER:
        setContainer((org.xtext.projet.selemodel.selemodel.Container)null);
        return;
      case SelemodelPackage.ATTRIBUT__CHAMP:
        setChamp(CHAMP_EDEFAULT);
        return;
      case SelemodelPackage.ATTRIBUT__LEN:
        setLen(LEN_EDEFAULT);
        return;
      case SelemodelPackage.ATTRIBUT__CONTAINERS:
        setContainers((Containers)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SelemodelPackage.ATTRIBUT__CONTAINER:
        return container != null;
      case SelemodelPackage.ATTRIBUT__CHAMP:
        return CHAMP_EDEFAULT == null ? champ != null : !CHAMP_EDEFAULT.equals(champ);
      case SelemodelPackage.ATTRIBUT__LEN:
        return LEN_EDEFAULT == null ? len != null : !LEN_EDEFAULT.equals(len);
      case SelemodelPackage.ATTRIBUT__CONTAINERS:
        return containers != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (champ: ");
    result.append(champ);
    result.append(", len: ");
    result.append(len);
    result.append(')');
    return result.toString();
  }

} //AttributImpl
