/**
 * generated by Xtext 2.10.0
 */
package org.xtext.projet.selemodel.selemodel.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.projet.selemodel.selemodel.Attribuable;
import org.xtext.projet.selemodel.selemodel.Declaration;
import org.xtext.projet.selemodel.selemodel.DeclarationAttribution;
import org.xtext.projet.selemodel.selemodel.SelemodelPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Declaration Attribution</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.impl.DeclarationAttributionImpl#getDec <em>Dec</em>}</li>
 *   <li>{@link org.xtext.projet.selemodel.selemodel.impl.DeclarationAttributionImpl#getAttb <em>Attb</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DeclarationAttributionImpl extends MinimalEObjectImpl.Container implements DeclarationAttribution
{
  /**
   * The cached value of the '{@link #getDec() <em>Dec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDec()
   * @generated
   * @ordered
   */
  protected Declaration dec;

  /**
   * The cached value of the '{@link #getAttb() <em>Attb</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttb()
   * @generated
   * @ordered
   */
  protected Attribuable attb;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeclarationAttributionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return SelemodelPackage.Literals.DECLARATION_ATTRIBUTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Declaration getDec()
  {
    return dec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDec(Declaration newDec, NotificationChain msgs)
  {
    Declaration oldDec = dec;
    dec = newDec;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SelemodelPackage.DECLARATION_ATTRIBUTION__DEC, oldDec, newDec);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDec(Declaration newDec)
  {
    if (newDec != dec)
    {
      NotificationChain msgs = null;
      if (dec != null)
        msgs = ((InternalEObject)dec).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SelemodelPackage.DECLARATION_ATTRIBUTION__DEC, null, msgs);
      if (newDec != null)
        msgs = ((InternalEObject)newDec).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SelemodelPackage.DECLARATION_ATTRIBUTION__DEC, null, msgs);
      msgs = basicSetDec(newDec, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SelemodelPackage.DECLARATION_ATTRIBUTION__DEC, newDec, newDec));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribuable getAttb()
  {
    return attb;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAttb(Attribuable newAttb, NotificationChain msgs)
  {
    Attribuable oldAttb = attb;
    attb = newAttb;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, SelemodelPackage.DECLARATION_ATTRIBUTION__ATTB, oldAttb, newAttb);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAttb(Attribuable newAttb)
  {
    if (newAttb != attb)
    {
      NotificationChain msgs = null;
      if (attb != null)
        msgs = ((InternalEObject)attb).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - SelemodelPackage.DECLARATION_ATTRIBUTION__ATTB, null, msgs);
      if (newAttb != null)
        msgs = ((InternalEObject)newAttb).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - SelemodelPackage.DECLARATION_ATTRIBUTION__ATTB, null, msgs);
      msgs = basicSetAttb(newAttb, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, SelemodelPackage.DECLARATION_ATTRIBUTION__ATTB, newAttb, newAttb));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case SelemodelPackage.DECLARATION_ATTRIBUTION__DEC:
        return basicSetDec(null, msgs);
      case SelemodelPackage.DECLARATION_ATTRIBUTION__ATTB:
        return basicSetAttb(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case SelemodelPackage.DECLARATION_ATTRIBUTION__DEC:
        return getDec();
      case SelemodelPackage.DECLARATION_ATTRIBUTION__ATTB:
        return getAttb();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case SelemodelPackage.DECLARATION_ATTRIBUTION__DEC:
        setDec((Declaration)newValue);
        return;
      case SelemodelPackage.DECLARATION_ATTRIBUTION__ATTB:
        setAttb((Attribuable)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case SelemodelPackage.DECLARATION_ATTRIBUTION__DEC:
        setDec((Declaration)null);
        return;
      case SelemodelPackage.DECLARATION_ATTRIBUTION__ATTB:
        setAttb((Attribuable)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case SelemodelPackage.DECLARATION_ATTRIBUTION__DEC:
        return dec != null;
      case SelemodelPackage.DECLARATION_ATTRIBUTION__ATTB:
        return attb != null;
    }
    return super.eIsSet(featureID);
  }

} //DeclarationAttributionImpl
