/**
 * generated by Xtext 2.10.0
 */
package org.xtext.selenium.selemodel.validation;

import org.xtext.selenium.selemodel.validation.AbstractSeleModelValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SeleModelValidator extends AbstractSeleModelValidator {
}
